"""Core audio processing utilities."""

from triton.core.mixer import mix_at_snr
from triton.core.signal import extract_envelope, bandpass_filter, to_mono_float32
from triton.core.io import (
    load_audio,
    save_audio,
    is_audio_file,
    iter_audio_files,
    iter_source_audio,
    normalize_peak,
    normalize_rms,
    rms,
    SUPPORTED_EXTS,
)
from triton.core.conversion import to_mono, to_stereo, resample, requantize
from triton.core.spectrogram import (
    SpectrogramResult,
    compute_spectrogram,
    load_spectrogram,
    normalize_spectrogram_settings,
    save_spectrogram,
)
from triton.core.project import (
    Project,
    PROJECT_CONFIG_NAME,
    SUPPORTED_AUDIO_SUFFIXES,
    project_config_path,
    project_raw_dir,
    initialize_project_tree,
    write_project_config,
    load_project_config,
    create_project,
    load_recent_projects,
    save_recent_projects,
    register_recent_project,
    list_project_files,
    add_project_file,
    delete_project_file,
    rename_project_file,
    sanitize_filename,
)
from triton.core.pipeline_runtime import (
    PIPELINE_ACTIONS,
    PIPELINE_STEP_ORDER,
    PIPELINE_DEFAULT_STEP,
    pipeline_action_label,
    default_step_options,
    pipeline_key,
    pipeline_output_dir,
    pipeline_run_dir,
    new_pipeline_run_id,
    apply_pipeline_step,
    run_pipeline_on_file,
)
from triton.core.pipeline_matrix import (
    MATRIX_FILE_COLUMN,
    parse_parameter_specs,
    generate_matrix_csv,
    run_matrix_csv,
)

__all__ = [
    "mix_at_snr",
    "extract_envelope",
    "bandpass_filter",
    "to_mono_float32",
    "load_audio",
    "save_audio",
    "is_audio_file",
    "iter_audio_files",
    "iter_source_audio",
    "normalize_peak",
    "normalize_rms",
    "rms",
    "SUPPORTED_EXTS",
    "to_mono",
    "to_stereo",
    "resample",
    "requantize",
    "SpectrogramResult",
    "compute_spectrogram",
    "load_spectrogram",
    "normalize_spectrogram_settings",
    "save_spectrogram",
    "Project",
    "PROJECT_CONFIG_NAME",
    "SUPPORTED_AUDIO_SUFFIXES",
    "project_config_path",
    "project_raw_dir",
    "initialize_project_tree",
    "write_project_config",
    "load_project_config",
    "create_project",
    "load_recent_projects",
    "save_recent_projects",
    "register_recent_project",
    "list_project_files",
    "add_project_file",
    "delete_project_file",
    "rename_project_file",
    "sanitize_filename",
    "PIPELINE_ACTIONS",
    "PIPELINE_STEP_ORDER",
    "PIPELINE_DEFAULT_STEP",
    "pipeline_action_label",
    "default_step_options",
    "pipeline_key",
    "pipeline_output_dir",
    "pipeline_run_dir",
    "new_pipeline_run_id",
    "apply_pipeline_step",
    "run_pipeline_on_file",
    "MATRIX_FILE_COLUMN",
    "parse_parameter_specs",
    "generate_matrix_csv",
    "run_matrix_csv",
]
